{
 "title": "Chicago Taxi Prediction Dashboard",
 "description": "The dashboard of Chicago Taxi prediction using Machine Learning model. ",
 "time": { "from": "2025-07-29T10:34:43.394Z", "to": "2025-07-29T11:06:38.277Z" },
 "panels": [
  {
   "title": "Ride Predictions Over Time",
   "type": "timeseries",
   "description": "This time series chart shown the ride prediction of Chicago taxi over time. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  predicted_duration\nFROM ride_predictions\nWHERE created_at >= NOW() - INTERVAL '1 hour'  -- optional filter\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Count of Rides Per 2-Minute Interval",
   "type": "barchart",
   "description": "This bar chart shown the number of ride per 2 minutes. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', created_at) AS time,\n  COUNT(*) as predictions_made\nFROM ride_predictions\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Distribution of Fare per Mile",
   "type": "histogram",
   "description": "This shown the distribution of fare per miles ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  fare / NULLIF(trip_miles, 0) AS fare_per_mile\nFROM ride_predictions\nWHERE trip_miles > 0"
    }
   ]
  },
  {
   "title": "Top PU_DO Routes",
   "type": "barchart",
   "description": "This bar chart shown the top Pickup and Dropoff Location. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(pickup_community_area, '_', dropoff_community_area) AS route,\n  COUNT(*) as rides\nFROM ride_predictions\nGROUP BY route\nORDER BY rides DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "5 Latest Prediction",
   "type": "table",
   "description": "This table shown the 5 latest prediction information. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  trip_id, predicted_duration, created_at\nFROM ride_predictions\nORDER BY created_at DESC\nLIMIT 5"
    }
   ]
  }
 ]
}