{
 "title": "Evidently Chicago Taxi Dashboard",
 "description": "This dashboard is to shown the prediction drift, missing column and number of drift column when predict chicago taxi duration",
 "time": { "from": "2023-01-31T11:00:00.000Z", "to": "2023-02-28T10:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "description": "The time series chart showing the prediction drift of Chicago Taxi Dataset on January 2023.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    \"timestamp\",\n    prediction_drift\nFROM \n    dummy_metrics\nWHERE \n    $__timeFilter(\"timestamp\")\nORDER BY \n    \"timestamp\""
    }
   ]
  },
  {
   "title": "Number of Drift Columns",
   "type": "timeseries",
   "description": "The time series chart showing the prediction drift of Chicago Taxi Dataset on January 2023.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp AS time,\n    num_drifted_columns\nFROM \n    dummy_metrics\nWHERE \n    $__timeFilter(timestamp)\nORDER BY \n    timestamp"
    }
   ]
  },
  {
   "title": "Number of Shared Missing Values",
   "type": "timeseries",
   "description": "The time series chart showing the number of shared missing value of Chicago Taxi Dataset on January 2023",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp AS time,\n    share_missing_values\nFROM \n    dummy_metrics\nWHERE \n    $__timeFilter(timestamp)\nORDER BY \n    timestamp"
    }
   ]
  }
 ]
}