apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: batch_db
    user: postgres
    secureJsonData:
      password: root
    jsonData: 
      sslmode: disable
    isDefault: true