channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - numpy==1.26.4
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.13.1
  - xgboost==2.1.4
name: mlflow-env
