version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: batch_db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080
