channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.13.1
name: mlflow-env
